services:
- type: pserv
  name: loggers
  plan: Free
  env: docker
  autoDeploy: false
  disk:
    name: loggers
    mountPath: /var/lib/mysql
    sizeGB: 10
  envVars:
  - fromGroup: loggers

envVarGroups:
- name: loggers
  envVars:
  - key: MYSQL_DATABASE
    value: loggers
  - key: MYSQL_USER
    value: loggers
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
